사용자 관련 기능 구현
2024GanzithonPYTHON/1_BACKEND pull request #1
Opened 2024-11-16 08:25 UTC by GO-p1sker

user관련 기능 구현

2024-11-16 08:26 UTC, GO-p1sker reviewed
[FEAT] 회원가입 로그인 로그아웃 기능 추가

2024-11-16 08:27 UTC, GO-p1sker reviewed
[FIX]  implementation 'jakarta.validation:jakarta.validation-api:3.0.2' 의존성 추가

2024-11-16 08:43 UTC, Zena0128 requested changes
댓글들 확인 부탁드립니다!

2024-11-16 08:43 UTC, Zena0128 commented on src/main/java/com/ganzithon/go_farming/configuration/SecurityConfig.java
> +		config.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "OPTIONS"));
PATCH도 추가해주시면 감사드리겠습니당

2024-11-16 08:43 UTC, Zena0128 commented on src/main/java/com/ganzithon/go_farming/user/User.java
> +    private List<Folder> folders; // 사용자가 생성한 폴더
지금 깃허브상에서는 Folder라는 객체가 없어서 이대로 머지하면 빌드 오류날 거라.. 이 필드는 주석처리한 후에 나중에 즐겨찾기 관련 기능 구현 완료 후에 주석 풀어주시면 될 것 같습니당

2024-11-16 08:43 UTC, Zena0128 commented on src/main/java/com/ganzithon/go_farming/user/UserController.java
> +public class UserController {
로그아웃 메소드는 의도적으로 작성하지 않으신 걸까여?

2024-11-16 09:24 UTC, GO-p1sker commented on src/main/java/com/ganzithon/go_farming/user/UserController.java
> +public class UserController {
컨트롤러에 로그아웃 메소드는 따로 작성안하고 리디렉션 기반으로 로그아웃을 동작했던 SecurityConfig를 JSON 방식 응답으로 수정했습니다

2024-11-17 08:46 UTC, Zena0128 approved these changes
확인했습니다!

2024-11-17 18:21 UTC, merged